[package]
name = "rust_nes"
version = "0.0.1"
authors = ["David Tyler <davet.code@gmail.com>"]
repository = "https://github.com/DaveTCode/nes-emulator-rust.git"
license = "MIT"
publish = false

[dependencies]
bitflags = "1.2.1"
log = "0.4.11"
log4rs = "1.0.0-alpha-2"
zip = "0.5.8"

[dev-dependencies]
crc32fast = "1.2.1"
criterion = "0.3.3"

[[bench]]
name = "benchmarks"
harness = false

[lib]
name = "rust_nes"
path = "src/lib.rs"