refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{m}{n}"
  file:
    kind: file
    path: "log/all.log"
  nes_test:
    kind: file
    path: "log/cpu.log"
    encoder:
      pattern: "{m}{n}"

root:
  level: info

loggers:
  rust_nes::cpu:
    level: error
    appenders:
      - file
  rust_nes::ppu:
    level: error
    appenders:
      - file
  rust_nes::cartridge:
    level: error
    appenders:
      - file
  rust_nes::io:
    level: error
    appenders:
      - file