refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{m}{n}"
  file:
    kind: file
    path: "log/all.log"
  nes_test:
    kind: file
    path: "log/cpu.log"
    encoder:
      pattern: "{m}{n}"

root:
  level: error
  appenders:
    - file

loggers:
  rust_nes::apu:
    level: debug
  rust_nes::cpu:
    level: info
  rust_nes::ppu:
    level: error
  rust_nes::cartridge:
    level: error
  rust_nes::io:
    level: error
